### ISSUE TITLE
security vulnerabilities (insecure randomness and ReDoS)

### ISSUE THREAD

**Issue by ChisholmKyle** [SocketCluster/socketcluster-server#19]
There are security vulnerabilities in the dependency **ws** and **sc-auth > jsonwebtoken > ms**
The snyk report has details here:
[https://snyk.io/test/npm/socketcluster-server/5.11.0](https://snyk.io/test/npm/socketcluster-server/5.11.0)

**Comment by jondubois** [comment]
The first issue should not affect SC if you use it with the `uws` module (which is the default). Also the second issue should not affect SC except maybe for some very specific undocumented scenarios because SC stores all durations as numbers in milliseconds and they always come from the server side (so the clients cannot use it to DoS the server).

But I'll update the `ws` and `jsonwebtoken` modules to the latest versions anyway to account for more exotic use cases.

**Comment by jondubois** [comment]
@ChisholmKyle Ok I have updated ws and jsonwebtoken.
